---
driver:
  name: docker

platforms:
- name: ubuntu-14.04
  driver_config:
    image: okapies/chef-solo
    platform: ubuntu
    use_sudo: false

suites:
  - name: default
    run_list:
      - recipe[dnvm::dnvm]
    attributes:
      dnvm:
        user: kitchen

